export const CHANGE_CURRENCY_ONE = 'CHANGE_CURRENCY_ONE'
export const CHANGE_VALUE_ONE = 'CHANGE_VALUE_ONE'
export const CHANGE_CURRENCY_TWO = 'CHANGE_CURRENCY_TWO'
export const CHANGE_VALUE_TWO = 'CHANGE_VALUE_TWO'
